### ISSUE TITLE
get_q_state error

### ISSUE THREAD

**Issue by xenhua** [VlachosGroup/pMuTT#111]
Hi Jon,

I have the following lines in my code:

```
for reaction_data in reactions_data:
    reaction = ChemkinReaction.from_string(species=species_dict, reaction_delimiter='=>', **reaction_data)
    print('-------------------------------------------------------------------')
    print(reaction_data)

    # Calculate forward reaction preexponential factor
    A_rxn_fwd = reaction.get_A(T=923.15,use_q=True)
    print('forward reaction preexponential factor A1_fwd(T = 923.15 K) = {:.3e}'.format(A_rxn_fwd))

    #Calculate Reactant Partition function
    reactant_q = reaction.get_q_state(state='reactants')
    print('Reactant Partition function (T = 923.15 K) = {:.3e}'.format(reactant_q))

    #Calculate Transition State partition function
    transition_state_q = reaction.get_q_state(state='transition_state', T=923.15)
    print('Transition State Partition function (T = 923.15 K) = {:.3e}'.format(transition_state_q))

    T = 923.15 # Kelvin
    planck = pmutt.constants.h(units='kJs',bar=False)
    Boltz = pmutt.constants.kb(units='kJ/K')

    kbT_over_h = (Boltz * T)/planck
    qts_over_qreactants = (transition_state_q)/(reactant_q)

    calc_pref = (kbT_over_h)*(qts_over_qreactants)

    print('calculated Prefactor = {:.3e}'.format(calc_pref))

```
My idea is basically to let pmutt calculate the prefactor automatically and then use Eqn.10 in your 

_Computer Physics Communication_

 paper to calculate each term individually and verify that both are equal.

But, I am getting an error in `get_q_state`. The following is the traceback.

```
Traceback (most recent call last):
  File "new_script.py", line 129, in <module>
    reactant_q = reaction.get_q_state(state='reactants', T=923.15)
  File "/home/xenhua/.local/lib/python3.6/site-packages/pmutt/reaction/__init__.py", line 184, in get_q_state
    **kwargs)
  File "/home/xenhua/.local/lib/python3.6/site-packages/pmutt/reaction/__init__.py", line 1673, in get_state_quantity
    method = getattr(specie, method_name)
AttributeError: 'Nasa' object has no attribute 'get_q'

```
Could you please take a look and let me know where I might be going wrong.

Thanks.

**Comment by jonlym** [comment]
Great questions! 

> My idea is basically to let pmutt calculate the prefactor automatically and then use Eqn.10 in your Computer Physics Communication paper to calculate each term individually and verify that both are equal.

It's always a good idea to double-check things. I think it should be the same ([see here for the source code for calculating the pre-exponential using partition functions](https://github.com/VlachosGroup/pMuTT/blob/master/pmutt/reaction/__init__.py#L1592)). 

> AttributeError: 'Nasa' object has no attribute 'get_q'

`Reaction` objects can only calculate properties that their constituents can calculate. In this case, converting a `StatMech` to a `Nasa` object removes the ability to calculate the partition function. So earlier in your code, you create `Nasa` objects using this:
```Nasa.from_model(...)```

but instead should be creating `StatMech` objects using this:
```StatMech(...)```

Let me know if that makes sense.

**Comment by xenhua** [comment]
I am attaching my complete script to this message. 

I previously had `line 44` in the script. I have now commented out `line 44` and inserted the `line 45` in the script. Please let me know if this is right.

This is still giving me error

> AttributeError: 'StatMech' object has no attribute 'phase'

in line 97 of my script on 

> reaction = ChemkinReaction.from_string(species=species_dict, reaction_delimiter='=>', **reaction_data)

Thank you so much.


[new_script.py.txt](https://github.com/VlachosGroup/pMuTT/files/3725304/new_script.py.txt)

**Comment by jonlym** [comment]
The changes you made are inline with my suggestion. However, ``ChemkinReactions`` was not really designed to accept ``StatMech``. Its purpose really is to write Chemkin input files from ``Nasa`` objects.

I'm afraid that means you should undo the change I suggested and all the pre-exponential factors will be calculated using the entropy of activation instead of partition functions in the Chemkin format.

i.e. ![Capture](https://user-images.githubusercontent.com/16866381/66770417-99359f00-ee85-11e9-9bd5-f1e56ee6629a.PNG)

where σ is the site density, and n is the number of surface species in the reaction.

This may be slightly different from the partition function example as discussed in #42 but perhaps not different enough to significantly change your rates.

**Comment by xenhua** [comment]
Hi Jon,

Thank you so much for your clarification.

I apologize for the delay in getting back to you.

Xenhua
