### ISSUE TITLE
Creation of Nasa object from model using a Shomate empirical model fails

### ISSUE THREAD

**Issue by wittregr** [VlachosGroup/pMuTT#113]
```from pmutt.empirical.nasa import Nasa
from pmutt.empirical.shomate import Shomate

gg = Shomate('CO2', 298., 1200., [5.974511, 13.19, -8.052431, 1.899711, -0.032657, -96.46451, 54.55141, -94.05411], phase='g', elements={'C':1,'O':2})

NN=[]

NN.append(Nasa.from_model(model=gg))
```

> Traceback (most recent call last):
>   File "<ipython-input-5-f349475a4a9b>", line 1, in <module>
>     NN.append(Nasa.from_model(model=gg))
> 
>   File "C:\Users\gerhard\Anaconda3\lib\site-packages\pmutt\empirical\nasa.py", line 614, in from_model
>     model=model, elements=elements, **kwargs)
> 
>   File "C:\Users\gerhard\Anaconda3\lib\site-packages\pmutt\empirical\nasa.py", line 431, in from_data
>     a_low, a_high, T_mid_out = _fit_CpoR(T=T, CpoR=CpoR, T_mid=T_mid)
> 
>   File "C:\Users\gerhard\Anaconda3\lib\site-packages\pmutt\empirical\nasa.py", line 1460, in _fit_CpoR
>     (mse, a_low, a_high) = _get_CpoR_MSE(T=T, CpoR=CpoR, T_mid=T_m)
> 
>   File "C:\Users\gerhard\Anaconda3\lib\site-packages\pmutt\empirical\nasa.py", line 1526, in _get_CpoR_MSE
>     p_low = np.polyfit(x=T_low, y=CpoR_low, deg=4)
> 
>   File "C:\Users\gerhard\Anaconda3\lib\site-packages\numpy\lib\polynomial.py", line 628, in polyfit
>     c, resids, rank, s = lstsq(lhs, rhs, rcond)
> 
>   File "C:\Users\gerhard\Anaconda3\lib\site-packages\numpy\linalg\linalg.py", line 2236, in lstsq
>     x, resids, rank, s = gufunc(a, b, rcond, signature=signature, extobj=extobj)
> 
> TypeError: No loop matching the specified signature and casting
> was found for ufunc lstsq_n
>

**Comment by jonlym** [comment]
This is likely due to the dimensions of T and CpoR that were fed into _get_CpoR_MSE. Will fix.

**Comment by wittregr** [comment]
This also fails when creating a Nasa empirical object from data with the same error. I assume that a function common to both is failing.

T=np.linspace(298, 1200, 1000)

NN.append(Nasa.from_data('CO', T, gg.get_CpoR(T), 298.15, gg.get_HoRT(298.15), gg.get_SoR(298.15), elements={'C': 1, 'O': 1,}, phase='g'))
Traceback (most recent call last):

  File "<ipython-input-17-48af1327c5b5>", line 1, in <module>
    NN.append(Nasa.from_data('CO', T, gg.get_CpoR(T), 298.15, gg.get_HoRT(298.15), gg.get_SoR(298.15), elements={'C': 1, 'O': 1,}, phase='g'))

  File "C:\Users\gerhard\Anaconda3\lib\site-packages\pmutt\empirical\nasa.py", line 431, in from_data
    a_low, a_high, T_mid_out = _fit_CpoR(T=T, CpoR=CpoR, T_mid=T_mid)

  File "C:\Users\gerhard\Anaconda3\lib\site-packages\pmutt\empirical\nasa.py", line 1460, in _fit_CpoR
    (mse, a_low, a_high) = _get_CpoR_MSE(T=T, CpoR=CpoR, T_mid=T_m)

  File "C:\Users\gerhard\Anaconda3\lib\site-packages\pmutt\empirical\nasa.py", line 1526, in _get_CpoR_MSE
    p_low = np.polyfit(x=T_low, y=CpoR_low, deg=4)

  File "C:\Users\gerhard\Anaconda3\lib\site-packages\numpy\lib\polynomial.py", line 628, in polyfit
    c, resids, rank, s = lstsq(lhs, rhs, rcond)

  File "C:\Users\gerhard\Anaconda3\lib\site-packages\numpy\linalg\linalg.py", line 2236, in lstsq
    x, resids, rank, s = gufunc(a, b, rcond, signature=signature, extobj=extobj)

TypeError: No loop matching the specified signature and casting
was found for ufunc lstsq_n

**Comment by jonlym** [comment]
The error arises due to elements of numpy arrays having type ``float`` instead of ``numpy.float64``. This occurred because the ``misc_models`` attribute was initialized using numpy's [``full_like``](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.full_like.html) function, which did not convert the type to the ``numpy.float64`` as expected. Previously, ``misc_models`` was an empty list so the incorrect unit type was irrelevant but in commit a4ff742, we created the ``GasPressureAdj`` object, which is automatically assigned to ``Nasa`` and ``Shomate`` objects when phase='G'.

To fix the issue, we explicitly passed the ``dtype`` to be a ``numpy.float64``
