### ISSUE TITLE
Error creating Nasa object from statmech

### ISSUE THREAD

**Issue by wittregr** [VlachosGroup/pMuTT#124]
```
runfile('C:/Users/gerhard/Documents/Gu GA/VASP_to_thermo_data.py', wdir='C:/Users/gerhard/Documents/Gu GA')
Traceback (most recent call last):

  File "<ipython-input-62-3c18c4614379>", line 1, in <module>
    runfile('C:/Users/gerhard/Documents/Gu GA/VASP_to_thermo_data.py', wdir='C:/Users/gerhard/Documents/Gu GA')

  File "C:\Users\gerhard\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\gerhard\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/gerhard/Documents/Gu GA/VASP_to_thermo_data.py", line 58, in <module>
    T_mid=T_mid, **specie_data) for specie_data in species_data]

  File "C:/Users/gerhard/Documents/Gu GA/VASP_to_thermo_data.py", line 58, in <listcomp>
    T_mid=T_mid, **specie_data) for specie_data in species_data]

  File "C:\Users\gerhard\Anaconda3\lib\site-packages\pmutt\empirical\nasa.py", line 512, in from_statmech
    references=references, **kwargs)

TypeError: from_data() got multiple values for keyword argument 'model'
```
**From this line in code:**
species = [Nasa.from_statmech(references=refs, T_low=T_low, T_high=T_high,
           T_mid=T_mid, **specie_data) for specie_data in species_data]

**Example specie_data:**
{'name': 'M110',
 'elements': {'C': 4, 'H': 4, 'O': 4},
 'phase': 'S',
 'statmech_model': pmutt.statmech.StatMech,
 'model': pmutt.statmech.StatMech,
 'vib_model': pmutt.statmech.vib.HarmonicVib,
 'elec_model': pmutt.statmech.elec.GroundStateElec,
 'required': ('vib_wavenumbers', 'potentialenergy', 'spin'),
 'potentialenergy': -77.26655153000002,
 'vib_wavenumbers': [3345.06412,
  3055.094993,
  3006.200428,
  2410.540371,
  1700.758634,
  1344.789226,
  1257.431373,
  1248.697746,
  1209.161819,
  1176.082711,
  1163.363553,
  1147.961052,
  1091.701019,
  1048.290951,
  937.24712,
  886.773912,
  749.950209,
  702.380201,
  618.017162,
  536.086243,
  508.312828,
  495.004018,
  452.775525,
  414.945419,
  368.321237,
  348.437229,
  318.916911,
  307.501661,
  292.270706,
  199.299329,
  186.720707,
  159.740492,
  135.929569,
  124.351394,
  85.875399,
  68.771848],
 'notes': 'Surface: Pt 4x4'}

**Temporary workaround**
del specie_data['model']

**Comment by jonlym** [comment]
Sorry about that. Looks like I forgot to update read_excel. Will make a hotfix version today.
