### ISSUE TITLE
AIChE Workshop

### ISSUE THREAD

**Issue by xenhua** [VlachosGroup/pMuTT#126]
Hi Jon,

I was seriously interested in attending the workshop on microkinetics as a part of the AIChE Annual Meeting. 
However, despite all my sincere efforts, I could not succeed in making it to the workshop.

Could you please let me know if I am going to miss out a lot by not attending this workshop. Is there any way that I can make-up for the absence in workshop. 

Thanks.

**Comment by jonlym** [comment]
Sorry to hear you won't be able to attend.

Is your institution a member of RAPID? I believe they will be livestreaming the event to RAPID members.

If not, I believe all the materials used in the workshop will be made available to the public.

**Comment by xenhua** [comment]
It's great to hear that the event will be livestreamed to RAPID members. I believe that my institution is already a RAPID member. 

I am looking forward to the event and the live stream.

Thank you.

**Comment by jonlym** [comment]
Great! I learned today that you still need to register but apply the coupon code to have the fee waived. So definitely look into registering if you haven't already!

**Comment by xenhua** [comment]
Thank you, Jon, for informing me. I will register for the event.

**Comment by jonlym** [comment]
I'm not sure if you were able to attend the workshop but [all the materials are available here](https://www.dropbox.com/sh/e1oozb6gzcanw3f/AAAekoHkTAdTy8VmBQTHO9VPa?dl=0). I believe the recording will be made available later too if you would prefer to watch that.
