### ISSUE TITLE
Arbitrarily Setting Pre-exponential Factor and Activation Energy for OpenMKM Reactions

### ISSUE THREAD

**Issue by jonlym** [VlachosGroup/pMuTT#150]
**Is your feature request related to a problem? Please describe.**
Currently, pMuTT relies on transition states to calculate the pre-exponential factor (A) and activation energy (Ea). However, most times literature data only provide the A and Ea directly, which requires users to do extra work to back-calculate the properties of the transition state.

**Describe the solution you'd like**
A new class where users can directly input A and Ea and it writes it to OpenMKM input files. The existing ``pmutt.omkm.SurfaceReaction`` class could be modified with a class method to create a transition state using the ``constants`` preset.

**Additional context**
@MaxRCohen, is there any other features related to this you would like to see?

**Comment by MaxRCohen** [comment]
I think this should cover it for this issue. I'll keep you informed as we encounter new issues in the literature data (like the non-linear coverage effects).

**Comment by jonlym** [comment]
``pmutt.omkm.SurfaceReaction`` now has the ``A`` and ``Ea`` attribute so users can specify kinetic parameters manually. To use in spreadsheets, just add two columns in the reaction sheet with the headers 'A' and 'Ea'.

Added to dev branch in commit 657915ba528316672b2082ff429c0917d9237c0a
Added to pMuTT version 1.2.20 in commit 0dd092f96941a244e14a96ef2b4da896b79dfb41
