### ISSUE TITLE
write_cti does not write sticking coefficients correctly

### ISSUE THREAD

**Issue by wittregr** [VlachosGroup/pMuTT#172]
**Version of pMuTT**
1.2.21

**Describe the bug**
write_cti writes 0.5 for the sticking coefficient regardless of the  entry in the input spreadsheet

**To Reproduce**
Run the attached python code using the attached input spreadsheet and thermdat file

**Expected behavior**
The thermo.cti file reaction should have the same sticking coefficient as in the spreadsheet

[ethane-odh-openMKM.zip](https://github.com/VlachosGroup/pMuTT/files/5038254/ethane-odh-openMKM.zip)

**Comment by jonlym** [comment]
Hi Gerhard, I think you missed the 'ethane_ch_BEP.xlsx' spreadsheet in the zip file.

**Comment by wittregr** [comment]
Oops. I’ll add it



--Gerhard

**Comment by wittregr** [comment]
Here is the input spreadsheet used to generate the error above.

[ethane-odh-openMKM.zip](https://github.com/VlachosGroup/pMuTT/files/5040946/ethane-odh-openMKM.zip)

**Comment by jonlym** [comment]
For adsorption reactions, pMuTT writes the [``sticking_coeff``](https://vlachosgroup.github.io/pMuTT/api/reactions/reactions/pmutt.omkm.reaction.SurfaceReaction.html?highlight=surfacereaction#pmutt.omkm.reaction.SurfaceReaction.sticking_coeff) parameter to the CTI file.

Try making a new column in your spreadsheet called 'sticking_coeff' instead of putting them in the 'A' column.

**Comment by wittregr** [comment]
Yes..That worked. I began wondering if sticking coefficients went in their
own column but I couldn't find any example or file spec that showed a
sticking_coeff column. Is there one that I missed?

Thanks

Gerhard R Wittreich, P.E.
Ph.D. Candidate, Vlachos Research Group
Harker ISE Lab-364
Chemical and Biomolecular Engineering, University of Delaware

**Comment by wittregr** [comment]
sticking coefficients need to be input in a column called sticking_coeff and not in the pre-exponential column.

**Comment by jonlym** [comment]
No, you're right. There are no examples that show it. It's worth modifying the openmkm_io example.
