### ISSUE TITLE
ImportError: cannot import name 'write_thermo_yaml' from 'pmutt.io.omkm'

### ISSUE THREAD

**Issue by lqcata** [VlachosGroup/pMuTT#182]
import pmutt 
print(pmutt.__version__)

1.2.21

-------------------------------------------
from pmutt.io.omkm import write_thermo__yaml

write_thermo_yaml(phases=phases,
                  species=species,
                  reactions=reactions,
                  lateral_interactions=interactions,
                  units=units,
                  filename='./outputs/thermo.yaml')
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-23-0410a37f7b77> in <module>
----> 1 from pmutt.io.omkm import write_thermo__yaml
      2 
      3 write_thermo_yaml(phases=phases,
      4                   species=species,
      5                   reactions=reactions,

ImportError: cannot import name 'write_thermo__yaml' from 'pmutt.io.omkm' (/home/dft/.local/lib/python3.7/site-packages/pmutt/io/omkm.py)

**Comment by jonlym** [comment]
Was this copied from an example? Your import statement has an extra '_'
i.e. "write_thermo__yaml"  should be "write_thermo_yaml"

**Comment by jonlym** [comment]
I think this issue is resolved so I'm closing it. Feel free to reopen it if you had any other questions related to it.

**Comment by lqcata** [comment]
> I think this issue is resolved so I'm closing it. Feel free to reopen it if you had any other questions related to it.

Thanks, I have checked it again.  The script works after removing the extra '_'.
