### ISSUE TITLE
omkm i/o Example failed due to the incorrect title in the xlsx file.

### ISSUE THREAD

**Issue by lqcata** [VlachosGroup/pMuTT#225]
**Version of pMuTT**
Please verify you are on the most updated version by comparing the [latest release on PyPI](https://pypi.org/project/pmutt/) to the output from the following:

```python
import pmutt
print(pmutt.__version__)
```
 - Version [e.g. 1.2.18]

**Describe the bug**

(base) qli@ISEL-LPF3FGKR9:~/caviness/mkm/H2$ python3 OpenMKM_IO.py 
Traceback (most recent call last):
  File "/home/win.udel.edu/qli/caviness/mkm/H2/OpenMKM_IO.py", line 148, in <module>
    write_yaml(filename=yaml_path, phases=phases, units=units, **reactor_data)
TypeError: write_yaml() got an unexpected keyword argument 'mode'
(base) qli@ISEL-LPF3FGKR9:~/caviness/mkm/H2$

**To Solve it**

Change the column title from 'mode' to 'temperature_mode' in the  "reactor" sheet in file:
https://github.com/VlachosGroup/pMuTT/blob/master/docs/source/examples_jupyter/omkm_io/inputs/NH3_Input_Data.xlsx

**Comment by wittregr** [comment]
You are running an old version of pMuTT. The current version is 1.4.4. The problem you described was corrected in a later version. Please, upgrade to the latest version to resolve this issue.
