### ISSUE TITLE
Does pMuTT support MESA?

### ISSUE THREAD

**Issue by arosen93** [VlachosGroup/pMuTT#231]
In Cohen and Vlachos, _Ind. Eng. Chem. Res._ (2022) [here](https://pubs.acs.org/doi/10.1021/acs.iecr.2c00390), the modified energy span analysis (MESA) is introduced. Is this approach included in pMuTT or another package from the Vlachos Group, out of curiosity?

Please feel free to close once answered. Thanks!!

**Comment by wittregr** [comment]
arosen93....Great question! Not yet, but I am working on that right now. As usual, other little problems have conspired to slow down my efforts. I hope to have that in place this summer.

**Comment by arosen93** [comment]
Awesome to hear! I wanted to make sure I wasn't missing anything :) Looking forward to the eventual addition!
