### ISSUE TITLE
Generation of surf.inp

### ISSUE THREAD

**Issue by MaxRCohen** [VlachosGroup/pMuTT#57]
The surf.inp file that gets generated includes the transition states in the species list at the top of the file, this results in these states being considered in the solution of the ODEs, can we set it up so only the ground states involved in the reactions Excel sheet are included at the top of the surf.inp file?

**Comment by jonlym** [comment]
> ... can we set it up so only the ground states involved in the reactions Excel sheet are included at the top of the surf.inp file?

When reading an Excel file using `pMuTT.io.excel.read_excel`, the `skiprows` argument allows you to skip lines. However, we changed pMuTT so the user isn't burdened to manually input transition state rows to skip.

Changed `pMuTT.io.chemkin.write_surf` so it does not accept `nasa_species`. Instead, it determines the surface species in the system from `reactions` (excluding transition states).
