### ISSUE TITLE
Chemkin_IO Example

### ISSUE THREAD

**Issue by SidraFirdous** [VlachosGroup/pMuTT#61]
Dear Authors,

Thank you for this software. 

I am trying  to reproduce your example of "Ammonia Synthesis" microkinetics, as listed in: "https://github.com/VlachosGroup/pMuTT/blob/master/docs/source/examples_jupyter/chemkin_io/"

I have a few questions regarding this example:

1. I see that "NH3 desorption" is actually listed as NH3 adsorption in the cell "A5" of the reactions sheet of the excel sheet of https://github.com/VlachosGroup/pMuTT/blob/master/docs/source/examples_jupyter/chemkin_io/inputs/NH3_Input_Data.xlsx, 
My question is how exactly are the adsorption and desorption rate constants calculated?

2. In this example, the energies in the cell H6 to H15 are the energies of the respective species on the surface (Ru0001) slab?

3. In the list of vibrational wave numbers, we don't include the imaginary frequencies of the ts or the ground states. Is that right?

Thanks.

**Comment by jonlym** [comment]
Hi @SidraFirdous,

Thank you for your interest.

1. This module was developed with the Vlachos' groups in-house Chemkin code so there may be differences when compared to Chemkin Pro. We calculate adsorption rate constants using Equation 56 in the [Chemkin III manual](http://www.cvd.louisville.edu/Course/Chemical%20Vapour%20Deposition/Manuals/chemkin/chemkin11surfacechemkin.pdf). The reverse rate constant (calculated by Chemkin and not pMuTT) can be found using Equation 36.

2. The energies have the slab contribution subtracted (i.e. E = E(slab + ads) - E(slab)). This is ultimately bookkeeping as we initialized our E(slab) to be 0.


3. If you include imaginary frequencies (as negative numbers), by default the vibrational modes will store them but ultimately ignore them when evaluating thermochemical properties.

Does that address your issue?

**Comment by SidraFirdous** [comment]
Dear Jonathan,
Thank you for the quick answers to my questions. They are up to the point and answer what I asked.

-  You are very right when you say, I am planning to use the files generated by using pMuTT with Chemkin-Pro. I believe vlachos group in-house Chemkin code is not available in the open domain? Could you please comment on this.

- Is it enough to specify only adsorption reaction on the "reactions" sheet of the excel sheet? I believe the desorption, (or all the reverse reacty

- I don't have much experience until now with Chemkin-Pro, do all the files written by pMuTT be sufficient to run a Chemkin simulation?

- How do you calculate the dimensionless (H/RT) heat capacity. 
For instance, I take R = 8.314 J mol-1 K-1, T = 298.15K, Specific heat of ammonia at 298.15 K = 37.0 Jmol-1 (Ref: https://www.engineeringtoolbox.com/ammonia-d_1413.html)
With these values H/RT comes as 0.0149 which is completely different from your value of -18.38.

Thanks.

**Comment by jonlym** [comment]
1. It is not open domain.

2. It is enough because all reactions are assumed to be reversible.

3. I'm unsure since I do not have any experience with Chemkin-Pro.

4. H/RT is the dimensionless enthalpy and not heat capacity. [The NIST estimate for heat of formation of NH3](https://webbook.nist.gov/cgi/cbook.cgi?ID=C7664417&Units=SI&Mask=1#Thermo-Gas) is -45.94 kJ/mol. Using R = 8.314e-3 kJ/mol/K and T = 298.15, you get a value of -18.53. (We'll have to update the example to match that).
