### ISSUE TITLE
KeyError: ' idealgas '

### ISSUE THREAD

**Issue by SidraFirdous** [VlachosGroup/pMuTT#62]
Dear Jonathan,

I am trying to reproduce the example from pMuTT located in "pMuTT/docs/source/examples_jupyter/chemkin_io"

I have prepared an excel sheet very similar to the one in the example and based on the python program, I have modified it to use my own data.

However, I encounter the below error:

> 
> {'bulk_specie': 'NI(B)',
>  'class': "<class 'pMuTT.chemkin.CatSite'>",
>  'density': 8.9,
>  'name': 'NI111',
>  'site_density': 3.095e-09}
> Traceback (most recent call last):
>   File "/home/sidra/.local/lib/python3.6/site-packages/pMuTT/io/excel.py", line 231, in set_statmech_model
>     output_structure.update(presets[model])
> KeyError: ' idealgas '
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "script.py", line 18, in <module>
>     references_data = read_excel(io=excel_path, sheet_name='refs')
>   File "/home/sidra/.local/lib/python3.6/site-packages/pMuTT/io/excel.py", line 97, in read_excel
>     output_structure=thermo_data)
>   File "/home/sidra/.local/lib/python3.6/site-packages/pMuTT/io/excel.py", line 235, in set_statmech_model
>     'models.'.format(model))
> ValueError: Unsupported thermodynamic model,  idealgas . See docstring of presets in pMuTT.statmech.presets for supported models.
> 

Could you please help me to solve this issue. Thank you so much.

Best regards,
Sidra

**Comment by jonlym** [comment]
It looks like you have a trailing space at the end of 'idealgas'. You should remove any spaces from the statmech_model column in your spreadsheet and see if the error still occurs.

**Comment by SidraFirdous** [comment]
Thank you so much for your quick response. 

I now get a new error. Could you please help me with understanding and troubleshooting this error.

> 
> {'bulk_specie': 'NI(B)',
>  'class': "<class 'pMuTT.chemkin.CatSite'>",
>  'density': 8.9,
>  'name': 'NI111',
>  'site_density': 3.095e-09}
> {'C': -515.0049233247561, 'H': -78.94000612426579, 'O': -83.44810159182849}
> /home/sidra/anaconda3/lib/python3.6/site-packages/scipy/stats/stats.py:1025: RuntimeWarning: invalid value encountered in double_scalars
>   return a.std(axis) / a.mean(axis)
> Traceback (most recent call last):
>   File "script.py", line 55, in <module>
>     reaction = ChemkinReaction.from_string(species=species_dict, **reaction_data)
>   File "/home/sidra/.local/lib/python3.6/site-packages/pMuTT/reaction/__init__.py", line 1766, in from_string
>     reactants = [species[name] for name in react_names]
>   File "/home/sidra/.local/lib/python3.6/site-packages/pMuTT/reaction/__init__.py", line 1766, in <listcomp>
>     reactants = [species[name] for name in react_names]
> KeyError: 'CO'

**Comment by jonlym** [comment]
It's hard to tell without seeing your spreadsheet and script but my guess is that you defined a reaction with CO but you do not have it available as a species. Make sure the key in the species dictionary exactly matches the name in the species sheet. (This could be similar to above where you have a trailing space)

**Comment by SidraFirdous** [comment]
With a polite request for the confidentiality of the numbers in the spreadsheet, please find the spreadsheet and the script attached here.

My eyes do not see the inconsistency you mention. Maybe, you can spot it.

[DRM_Input_Data.xlsx](https://github.com/VlachosGroup/pMuTT/files/3169624/DRM_Input_Data.xlsx)

[script-py.txt](https://github.com/VlachosGroup/pMuTT/files/3169626/script-py.txt)

Thank you so much.

**Comment by jonlym** [comment]
In cell A5, you have 'CO ' (note the trailing space). The [TRIM function in Excel](https://support.office.com/en-us/article/trim-function-410388fa-c5df-49c6-b16c-9e5630b479f9) can remove leading and trailing spaces. Also, you can use the [LEN function in Excel](https://support.office.com/en-us/article/len-lenb-functions-29236f94-cedc-429d-affd-b5e33d2c67cb) to check for spaces that are hard to see by eye.

**Comment by SidraFirdous** [comment]
Thank you so much for your help. 

Now, a new error. Please hints on how to solve this:

> {'bulk_specie': 'NI(B)',
>  'class': "<class 'pMuTT.chemkin.CatSite'>",
>  'density': 8.9,
>  'name': 'NI111',
>  'site_density': 3.095e-09}
> {'C': -515.0049233247561, 'H': -78.94000612426579, 'O': -83.44810159182849}
> /home/sidra/anaconda3/lib/python3.6/site-packages/scipy/stats/stats.py:1025: RuntimeWarning: invalid value encountered in double_scalars
>   return a.std(axis) / a.mean(axis)
> Traceback (most recent call last):
>   File "script.py", line 66, in <module>
>     ck_io.write_surf(filename='./outputs/surf.inp', reactions=reactions, act_method_name='get_GoRT_act')
> TypeError: write_surf() missing 1 required positional argument: 'nasa_species'
>

**Comment by SidraFirdous** [comment]
I have addresed this by modifying line 66 of the script as: 

`ck_io.write_surf(filename='./outputs/surf.inp', nasa_species=species, reactions=reactions, act_method_name='get_GoRT_act')
`

**Comment by jonlym** [comment]
What version of pMuTT are you using? You can check by running a script with the following:
```
import pMuTT
print(pMuTT.__version__)
```

The examples were written for the most recent version (1.2.6) where we recently made a change so `write_surf` no longer requires `nasa_species`. You can update pMuTT by typing the following in an Anaconda prompt or some command line terminal:
`pip install --user pMuTT --upgrade`

**Comment by SidraFirdous** [comment]
The version it says is 1.2.3.

Thank you, I upgraded pMuTT.

I have a question, 
the 'surf.inp' file written by pMuTT has all the prefactors same for all the surface reactions. Is it supposed to be like this, or is there any error in it?
[surf.inp.txt](https://github.com/VlachosGroup/pMuTT/files/3169655/surf.inp.txt)

Thanks

**Comment by jonlym** [comment]
Since you specified your `act_method_name` to be `get_GoRT_act`, the activation energy column includes enthalpy and entropy. If you had specified a different method (like `get_EoRT`) then the entropic contribution would be included in the preexponential factor.

As a side note, you should use a dimensional `act_method_name` (i.e. use `get_G` instead of `get_GoRT`). Chemkin's surf.inp file does not support dimensionless units.

**Comment by SidraFirdous** [comment]
Thank you for the clarification.

What you are saying is that the final rate constant will be the same for both the methods?

**Comment by jonlym** [comment]
Yup!

**Comment by SidraFirdous** [comment]
Thank you so much for your help.
