### ISSUE TITLE
act_method_name

### ISSUE THREAD

**Issue by SidraFirdous** [VlachosGroup/pMuTT#65]
Dear Jonathan,

As per one of your earlier suggestions, I am trying to use `act_method_name='get_G'`, and I am encountering the following error:

`{'bulk_specie': 'NI(B)',
 'class': "<class 'pMuTT.chemkin.CatSite'>",
 'density': 8.9,
 'name': 'NI111',
 'site_density': 3.095e-09}
{'C': -394.94046028748585, 'H': -107.75547725321074, 'O': -165.091936457172}
/home/sidra/anaconda3/lib/python3.6/site-packages/scipy/stats/stats.py:1025: RuntimeWarning: invalid value encountered in double_scalars
  return a.std(axis) / a.mean(axis)
Traceback (most recent call last):
  File "script.py", line 66, in <module>
    ck_io.write_surf(filename='./outputs_withH2O/surf.inp', reactions=reactions, act_method_name='get_G')
  File "/home/sidra/.local/lib/python3.6/site-packages/pMuTT/io/chemkin.py", line 366, in write_surf
    sden_operation=sden_operation, **kwargs)
  File "/home/sidra/.local/lib/python3.6/site-packages/pMuTT/io/chemkin.py", line 709, in _write_reaction_lines
    Ea_method = getattr(reaction, act_method_name)
AttributeError: 'ChemkinReaction' object has no attribute 'get_G'
`

Could you please advise me on how to overcome this error. Thank you.

Best regards,
Sidra

**Comment by jonlym** [comment]
I think I misspoke. Can you try using ``get_G_act`` instead?

**Comment by SidraFirdous** [comment]
I am trying `get_G_act`. Again I face an error:

`{'bulk_specie': 'NI(B)',
 'class': "<class 'pMuTT.chemkin.CatSite'>",
 'density': 8.9,
 'name': 'NI111',
 'site_density': 3.095e-09}
{'C': -394.94046028748585, 'H': -107.75547725321074, 'O': -165.091936457172}
/home/sidra/anaconda3/lib/python3.6/site-packages/scipy/stats/stats.py:1025: RuntimeWarning: invalid value encountered in double_scalars
  return a.std(axis) / a.mean(axis)
Traceback (most recent call last):
  File "script.py", line 66, in <module>
    ck_io.write_surf(filename='./outputs_withH2O/surf.inp', reactions=reactions, act_method_name='get_G_act')
  File "/home/sidra/.local/lib/python3.6/site-packages/pMuTT/io/chemkin.py", line 366, in write_surf
    sden_operation=sden_operation, **kwargs)
  File "/home/sidra/.local/lib/python3.6/site-packages/pMuTT/io/chemkin.py", line 711, in _write_reaction_lines
    Ea = _force_pass_arguments(Ea_method, **kwargs)
  File "/home/sidra/.local/lib/python3.6/site-packages/pMuTT/__init__.py", line 445, in _force_pass_arguments
    return fn(**kwargs)
  File "/home/sidra/.local/lib/python3.6/site-packages/pMuTT/reaction/__init__.py", line 1438, in get_G_act
    return self.get_delta_G(units=units, T=T, rev=rev, act=True, **kwargs)
  File "/home/sidra/.local/lib/python3.6/site-packages/pMuTT/reaction/__init__.py", line 1095, in get_delta_G
    **kwargs)*T*c.R('{}/K'.format(units))
  File "/home/sidra/.local/lib/python3.6/site-packages/pMuTT/reaction/__init__.py", line 1066, in get_delta_GoRT
    **kwargs)
  File "/home/sidra/.local/lib/python3.6/site-packages/pMuTT/reaction/__init__.py", line 1715, in get_delta_quantity
    **kwargs)
  File "/home/sidra/.local/lib/python3.6/site-packages/pMuTT/reaction/__init__.py", line 1666, in get_state_quantity
    for specie, stoich in zip(species, stoich):
TypeError: zip argument #1 must support iteration`

**Comment by jonlym** [comment]
> TypeError: zip argument #1 must support iteration

Hm... to me this seems like your species (either reactants, products, or transition state) were not assigned correctly. Are the reactions you're using the same as the spreadsheet attached in Issue #62 ?

**Comment by SidraFirdous** [comment]
Yes, it is the same, albeit, I added a new gas phase species, H2O.
I am re-attaching it.
[DRM_Input_Data.xlsx](https://github.com/VlachosGroup/pMuTT/files/3218701/DRM_Input_Data.xlsx)

**Comment by jonlym** [comment]
Looking into it. Just an FYI, columns V through Z do not have column headers so this data is not being read. If they are vibrational frequencies, add `vib_wavenumber` in the 1st row.

**Comment by SidraFirdous** [comment]
Thank you for the hint. I have now added the headers.

Also, The newly added gas phase species H2O did not have any reaction associated with it. I have now corrected that also in esxcel sheet, but the error persists.
[DRM_Input_Data.xlsx](https://github.com/VlachosGroup/pMuTT/files/3218729/DRM_Input_Data.xlsx)

**Comment by jonlym** [comment]
I did not see any errors in your spreadsheet and I am not able to run your script without the CONTCAR files. Could you insert these lines before you write the Chemkin files and let me know what is printed out?

```
from pprint import pprint

for reaction in reactions:
    try:
        # See if reactions method can calculate Gibbs activation
        reaction.get_G_act(T=298., units='kcal/mol')
    except TypeError:
        # If it cannot, print the reaction and its structure
        print(str(reaction)) 
        pprint(reaction.to_dict())
```

**Comment by SidraFirdous** [comment]
I have redirected the stdout to out.dat and I am attaching it.

I can also attach contcar zips if required. Please let me know. 

[out.dat.txt](https://github.com/VlachosGroup/pMuTT/files/3218756/out.dat.txt)

**Comment by jonlym** [comment]
All the reactions are adsorption reactions. In your reactions sheet, can you change the contents of ``is_adsorption`` from "0" and "1" to "=FALSE" and "=TRUE" respectively?

**Comment by SidraFirdous** [comment]
I did what you suggested in the excel sheet. But, I don't see a lot of difference in the out2.dat.txt.

[DRM_Input_Data.xlsx](https://github.com/VlachosGroup/pMuTT/files/3218787/DRM_Input_Data.xlsx)
[out2.dat.txt](https://github.com/VlachosGroup/pMuTT/files/3218788/out2.dat.txt)

**Comment by jonlym** [comment]
Hm... I still think that column is the issue. The dictionary entries for is_adsorption are integers when they should be boolean.

I can't look at it right now but I'll come back to it.

**Comment by SidraFirdous** [comment]
Thank you. I will wait further for your advice. Just for your info, going back to `act_method_name='get_GoRT_act'` solves the issue and the chemkin files are written.

[script.py.txt](https://github.com/VlachosGroup/pMuTT/files/3218824/script.py.txt)

[CONTCARs.zip](https://github.com/VlachosGroup/pMuTT/files/3218823/CONTCARs.zip)

**Comment by SidraFirdous** [comment]
Dear Jonathan, 

Thank you for your continued support in the use of pMutt. 
Did you get a chance to take a look at the issue I’m facing regarding “act_method_name”. 
Do you have any suggestions for me. 

Best regards,
Sidra
