### ISSUE TITLE
ChemkinReaction.from string

### ISSUE THREAD

**Issue by spbatchu** [VlachosGroup/pMuTT#68]
Dear pMuTT file managers, 

I am working on writing a surf.inp file using excel data as input. The reaction is ethane DH to produce ethylene and H2.  The name of my excel file is 'Thermdat_2Ga_doped_H2O' and file type is .xlsx

 I basically read four sheets from my excel file namely references, cat_sites, species and reactions. The columns in each sheet are as follows: 

 references : 'name', 'column corresponding to each element in my reaction', 'statmech_model', 'T_ref','HoRT_ref', 'potentialenergy', 'geometry','atoms', 'symmetry', 'spin', vib_wavenumbers

cat_sites: 'name', 'site_density', 'density','bulk_speci'

species: 'name', 'phase', column corresponding to each element in my reaction, 'statmech_model', 'potentialenergy', 'geometry', 'atoms', 'symmetry','spin', vib_wavenumbers 

reactions: 'reaction_str', is_adsorption'

I read the 'reactions' sheet to make my reactions object as follows:

surf_rxns=read_excel(io='Thermdat_2Ga_doped_H2O.xlsx', sheetname='reactions')
rxns=Reactions(reactions=ChemkinReaction.from_string(species=species_dict, **rxn_data) for rxn_data in surf_rxns])

In the above lines, I do  not specify any sticking_coefficient argument for the '.from_string method'. This implies that in my surf.inp file that is created, the sticking_coefficient value is supposed to be 0.5 which is the default value. 

But, I see a sticking co-efficeint value of 1 instead. 

Kindly look into it.

**Comment by jonlym** [comment]
Thanks for pointing this out.

It looks like the default value for sticking coefficient `pMuTT.reaction.ChemkinReaction.from_string` is 1.0 whereas the default value is 0.5 for `pMuTT.reaction.ChemkinReaction`.

If you pass the sticking coefficients in your `from_string` function, does it output the correct value in surf.inp?

**Comment by spbatchu** [comment]
Yes, If I pass the sticking coefficients in 'from_string' function, it outputs the correct value in surf.inp.

Thanks

**Comment by jonlym** [comment]
Great! We'll include this bug fix in the next release. Thanks again.
