### ISSUE TITLE
 NAM minimal VirtualBox  OVA

### ISSUE THREAD

**Issue by xenhua** [VlachosGroup/pMuTT#80]
I have seen your issue about E_INVALIDARG. I am not having that issue, but I am facing other issue described below:

I am trying to go through the NAM minimal VirtualBox with the instructions provided in the dropbox folder. However, the 'bin' folder in minimal Virtualbox ova does not have ckinterp.x and skinterp.x.

**Comment by jonlym** [comment]
Thanks for your comment. The MKM software used for this session was only available during the NAM workshop. I will update the documentation to reflect that.

We are currently working on an open-source MKM tool. If you are interested in learning when that is released, please sign up for our mailing list by e-mailing me (jlym@udel.edu).
