### ISSUE TITLE
Co-adsorbed species

### ISSUE THREAD

**Issue by xenhua** [VlachosGroup/pMuTT#97]
Hi Jon,

I was just wondering how to approach this situation:

For instance, I need to calculate the forward and backward rate constants for a simple elementary reaction such as `CO(S) + NI(S) => C(S) + O(S) + NI(B)` where `NI(S)` and `NI(B)` are metal surface and bulk respectively.

The calculation of the forward rate constant for the forward reaction is fairly straight-forward. However, to calculate the backward rate constant, I believe pMuTT takes adsorbed C and adsorbed O at infinite separation as two species and use them for rate constant calculation. But, I also have the co-adsorbed state of C and O with their vibrational frequencies calculated. I would like to use this co-adsorbed state as a separate species in the `"species"` tab of the excel sheet and use it for the rate constant calculation.

How can I do this? Any suggestions?

Thank you.

**Comment by jonlym** [comment]
> However, to calculate the backward rate constant, I believe pMuTT takes adsorbed C and adsorbed O at infinite separation as two species and use them for rate constant calculation.

I agree with that. However, I think this is the nature of the mean-field assumption where you lose the spatial information of the C(S) and O(S).

If you've determined that the rate of your overall reaction (or other important metrics) would be significantly different when comparing infinite separation to adjacent adsorbates then perhaps you should use a technique like kinetic Monte Carlo.

If you still want to use a mean-field MKM, perhaps you can define a species of the co-adsorbated state (e.g. `C-O(2S)`) which would occupy 2 sites? But then you would need another reaction step defining the barrier to separate the adsorbates.
e.g. `C-O(2S) => C(S) + O(S)`

But I would be careful with this approach.

**Comment by xenhua** [comment]
Thanks Jon.

I completely agree with what you are saying. What you say makes complete sense.
I will continue with infinite separation between adsorbed species.
